apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-kube-prometheus-stack
  namespace: argocd
  labels:
    hyops.domain: observability
    hyops.app: kube-prometheus-stack
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  sources:
    - repoURL: REPLACE_CHART_REPO_URL
      chart: kube-prometheus-stack
      targetRevision: REPLACE_CHART_VERSION
      helm:
        valueFiles:
          - $values/apps/observability/kube-prometheus-stack/base/values.yaml
    - repoURL: REPLACE_GIT_REPO_URL
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
