apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-velero
  namespace: argocd
  labels:
    hyops.domain: platform
    hyops.app: velero
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  sources:
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      chart: velero
      targetRevision: 8.5.0
      helm:
        valueFiles:
          - $values/apps/platform/velero/base/values.yaml
    - repoURL: https://github.com/hybridops-tech/hybridops-workloads.git
      targetRevision: v0.1.0-stage1
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
