apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: business-zammad
  namespace: argocd
  labels:
    hyops.domain: business
    hyops.app: zammad
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: zammad
  sources:
    - repoURL: REPLACE_CHART_REPO_URL
      chart: zammad
      targetRevision: REPLACE_CHART_VERSION
      helm:
        valueFiles:
          - $values/apps/business/zammad/base/values.yaml
    - repoURL: REPLACE_GIT_REPO_URL
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
