apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-keycloak
  namespace: argocd
  labels:
    hyops.domain: platform
    hyops.app: keycloak
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  sources:
    - repoURL: REPLACE_CHART_REPO_URL
      chart: keycloak
      targetRevision: REPLACE_CHART_VERSION
      helm:
        valueFiles:
          - $values/apps/platform/keycloak/base/values.yaml
    - repoURL: REPLACE_GIT_REPO_URL
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
