apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: academy-website
  namespace: argocd
  labels:
    hyops.domain: academy
    hyops.app: website
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: academy
  sources:
    - repoURL: REPLACE_CHART_REPO_URL
      chart: website
      targetRevision: REPLACE_CHART_VERSION
      helm:
        valueFiles:
          - $values/apps/academy/website/base/values.yaml
    - repoURL: REPLACE_GIT_REPO_URL
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
