apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-thanos-compactor
  namespace: argocd
  labels:
    hyops.domain: observability
    hyops.app: thanos-compactor
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: thanos
      targetRevision: 17.2.0
      helm:
        valueFiles:
          - $values/apps/observability/thanos-compactor/base/values.yaml
    - repoURL: REPLACE_GIT_REPO_URL
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
