apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-loki
  namespace: argocd
  labels:
    hyops.domain: observability
    hyops.app: loki
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  sources:
    - repoURL: REPLACE_CHART_REPO_URL
      chart: loki
      targetRevision: REPLACE_CHART_VERSION
      helm:
        valueFiles:
          - $values/apps/observability/loki/base/values.yaml
    - repoURL: REPLACE_GIT_REPO_URL
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
