apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-loki
  namespace: argocd
  labels:
    hyops.domain: observability
    hyops.app: loki
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.24.0
      helm:
        valueFiles:
          - $values/apps/observability/loki/base/values.yaml
    - repoURL: https://github.com/hybridops-tech/hybridops-workloads.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
