apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: studio-docsgpt
  namespace: argocd
  labels:
    hyops.domain: studio
    hyops.app: docsgpt
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: docsgpt
  sources:
    - repoURL: REPLACE_CHART_REPO_URL
      chart: docsgpt
      targetRevision: REPLACE_CHART_VERSION
      helm:
        valueFiles:
          - $values/apps/studio/docsgpt/base/values.yaml
    - repoURL: REPLACE_GIT_REPO_URL
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
